version: '2.4'

services:
  react_native_app:
    image: your-image-registry/planner-front:latest
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    healthcheck:
      disable: true
